# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#   - board: nice_nano
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: nice_nano/nrf52840/zmk
    shield: flb36_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: flb36_left
  - board: nice_nano/nrf52840/zmk
    shield: flb36_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: flb36_right
  - board: nice_nano/nrf52840/zmk
    shield: flb36_dongle dongle_display
    artifact-name: flb36_dongle
  - board: nice_nano/nrf52840/zmk
    shield: flb36_dongle
    cmake-args: -DCONFIG_FLB36_I2C_TEST=y
    artifact-name: flb36_oled_raw_test
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset_keyboard
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset_dongle
